### ISSUE TITLE
Pages do not validate

### ISSUE THREAD

**Issue by PlumbersNearMe** [mdmower/amp-self-host-demo#1]
Hi, I'm sorry if this is the wrong place to ask, but I've tested implementing this on some of my website pages, and although I've done everything correctly (I think) it still doesn't pass amp validation testing tools. I noticed the examples here also do not pass validation, my question is - if I implement this and it is not passing amp validation, would my site suffer penalties in google search? Id like to implement it right now, because the benefits are clear. But not at the expense of a penalty.

**Comment by mdmower** [comment]
Right, AMP pages utilizing a self-hosted AMP framework do not yet pass validation. This is noted in the introduction to the [guide at ampproject](https://github.com/ampproject/amphtml/blob/master/spec/amp-framework-hosting.md). Feel free to watch or join the discussion at https://github.com/ampproject/amphtml/issues/27546.

As for the impact on Google search rankings, because your AMP pages don't validate, you won't get the [benefit of the lightning bolt](https://www.wompmobile.com/does-the-amp-lightning-bolt-badge-improve-click-through-rate-yes/) in search results, but your pages should still rank well in terms of speed.

**Comment by PlumbersNearMe** [comment]
Great! thanks for the quick and complete reply. Very much appreciated. I think I will go ahead and roll out the implementation.
